############################################################
## https://docs.prylabs.network/docs/prysm-usage/parameters/
############################################################

accept-terms-of-use: yes

datadir: /data

p2p-host-ip: ""
p2p-host-dns: ""

rpc-host: 0.0.0.0
monitoring-host: 0.0.0.0

# disable scan of local network
p2p-denylist: ["10.0.0.0/8","172.16.0.0/12","192.168.0.0/16","100.64.0.0/10","169.254.0.0/16"]

p2p-max-peers: 100

http-web3provider: http://geth:8545