
############################################################
## https://docs.prylabs.network/docs/prysm-usage/parameters/
############################################################

accept-terms-of-use: yes

beacon-rpc-provider: beacon:4000
monitoring-host: 0.0.0.0

datadir: /data/db
wallet-dir: /data/wallets
wallet-password-file: /data/passwords/wallet-password

graffiti: ""