{
 "title": "ETH staking dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "node_job", "query": "beacon node" },
   { "name": "validator_job", "query": "validator" },
   {
    "name": "fiat",
    "label": "Currency converter",
    "query": "label_values(crypto_currency, pair)"
   },
   { "name": "validator_launchpad", "query": "localhost:8081" },
   { "name": "validator_ethdo", "query": "localhost:8079" }
  ]
 },
 "panels": [
  {
   "title": "VALIDATOR",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Hourly earning",
   "type": "stat",
   "description": "This panel shows the earning during the last hour, and the annualized % of the hourly earning.\n\nThose data won't be shown until the first validator is at least one hour old, or that you started prometheus at least one hour ago.\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1h) - count(validator_balance > 16)*32 + count(validator_balance offset 1h > 0)*32)*absent(crypto_currency{pair=~\"eth$fiat\"})",
     "legendFormat": "ETH"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1h) - count(validator_balance > 16)*32 + count(validator_balance offset 1h > 0)*32)*sum(crypto_currency{pair=\"eth$fiat\"})",
     "legendFormat": "$fiat"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1h) - count(validator_balance > 16)*32 + count(validator_balance offset 1h > 0)*32)/(avg_over_time(count(validator_balance > 16)[1h:30s])*32/24/365)*100",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Daily earning",
   "type": "stat",
   "description": "This panel shows the earning during the last day, and the annualized % of the daily earning.\n\nThose data won't be shown until the first validator is at least one day old, or that you started prometheus at least one day ago.\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1d) - count(validator_balance > 16)*32 + count(validator_balance offset 1d > 0)*32)*absent(crypto_currency{pair=~\"eth$fiat\"})",
     "legendFormat": "ETH"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1d) - count(validator_balance > 16)*32 + count(validator_balance offset 1d > 0)*32)*sum(crypto_currency{pair=\"eth$fiat\"})",
     "legendFormat": "$fiat"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1d) - count(validator_balance > 16)*32 + count(validator_balance offset 1d > 0)*32)/(avg_over_time(count(validator_balance > 16)[1d:12m])*32/365)*100",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Weekly earning",
   "type": "stat",
   "description": "This panel shows the earning during the last week, and the annualized % of the weekly earning.\n\nThose data won't be shown until the first validator is at least one week old, or that you started prometheus at least one week ago.\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1w) - count(validator_balance > 16)*32 + count(validator_balance offset 1w > 0)*32)*absent(crypto_currency{pair=~\"eth$fiat\"})",
     "legendFormat": "ETH"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1w) - count(validator_balance > 16)*32 + count(validator_balance offset 1w > 0)*32)*sum(crypto_currency{pair=\"eth$fiat\"})",
     "legendFormat": "$fiat"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 1w) - count(validator_balance > 16)*32 + count(validator_balance offset 1w > 0)*32)/(avg_over_time(count(validator_balance > 16)[1w:84m])*32*7/365)*100",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Monthly earning",
   "type": "stat",
   "description": "This panel shows the earning during the last month, and the annualized % of the monthly earning.\n\nThose data won't be shown until the first validator is at least one month old, or that you started prometheus at least one month ago. Ensure to run Prometheus with the flag `--storage.tsdb.retention.time=31d` if you want this panel to get enough data\n\nAlso, the annualized % might be wrong if you have downtime while new validators are getting validated",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 30d) - count(validator_balance > 16)*32 + count(validator_balance offset 30d > 0)*32)*absent(crypto_currency{pair=~\"eth$fiat\"})",
     "legendFormat": "ETH"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 30d) - count(validator_balance > 16)*32 + count(validator_balance offset 30d > 0)*32)*sum(crypto_currency{pair=\"eth$fiat\"})",
     "legendFormat": "$fiat"
    },
    {
     "expr": "(sum(validator_balance) - sum(validator_balance offset 30d) - count(validator_balance > 16)*32 + count(validator_balance offset 30d > 0)*32)/(avg_over_time(count(validator_balance > 16)[30d:6h])*32/12)*100",
     "legendFormat": "Annualized %"
    }
   ]
  },
  {
   "title": "Total earning",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(validator_balance) - count(validator_balance > 16 and validator_statuses == 3)*32*absent(crypto_currency{pair=~\"eth$fiat\"})",
     "legendFormat": "ETH"
    },
    {
     "expr": "(sum(validator_balance) - count(validator_balance > 16 and validator_statuses == 3)*32)*sum(crypto_currency{pair=\"eth$fiat\"})",
     "legendFormat": "$fiat"
    },
    {
     "expr": "(sum(validator_balance) - count(validator_balance > 16 and validator_statuses == 3)*32)*100/(count(validator_balance > 16 and validator_statuses == 3)*32)",
     "legendFormat": "ROI"
    }
   ]
  },
  {
   "title": "Validator process started",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"$validator_job\"})/3600",
     "legendFormat": "launchpad"
    }
   ]
  },
  {
   "title": "Total balance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    { "expr": "sum(validator_balance > 16)", "legendFormat": "Total balance" }
   ]
  },
  {
   "title": "Validator balance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "label_replace(validator_balance > 16, \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")",
     "legendFormat": "{{pubkey}}"
    }
   ]
  },
  {
   "title": "Validator main info",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "label_replace(max by(pubkey) (validator_balance), \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_statuses), \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    }
   ]
  },
  {
   "title": "Validator vote summary",
   "type": "table-old",
   "description": "This panel will count only the votes done since your validator process started",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "label_replace(max by(pubkey) (validator_successful_attestations) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey)(validator_failed_attestations)  , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey)(validator_successful_aggregations)    , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey) (validator_failed_aggregations) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey) (validator_successful_proposals) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey) (validator_failed_proposals) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    }
   ]
  },
  {
   "title": "BOTH",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1", "legendFormat": "NODE" }
   ]
  },
  {
   "title": "NODE",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 11, "x": 8, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1", "legendFormat": "NODE" }
   ]
  },
  {
   "title": "ALERTS",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Hardware usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes", "label": "mem usage" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(process_resident_memory_bytes{job=\"$node_job\"}[1m:5s])",
     "legendFormat": "memory {{job}}"
    },
    {
     "expr": "avg_over_time(process_resident_memory_bytes{job=\"$validator_job\"}[1m:5s])",
     "legendFormat": "memory {{job}} {{instance}}"
    },
    {
     "expr": "((process_cpu_seconds_total{job=\"$node_job\"} - process_cpu_seconds_total{job=\"$node_job\"} offset 2m) > 0)*100/120/go_maxprocs{job=\"$node_job\"}",
     "legendFormat": "CPU {{job}}"
    },
    {
     "expr": "((process_cpu_seconds_total{job=\"$validator_job\"} - process_cpu_seconds_total{job=\"$validator_job\"} offset 2m) > 0)*100/120/go_maxprocs{job=\"$validator_job\"}",
     "legendFormat": "CPU {{job}} {{instance}}"
    }
   ]
  },
  {
   "title": "Balance validators status and participation rate",
   "type": "graph",
   "description": "This graph is made for trading purpose mostly.\nSupposing that if a lot of validators are exiting, price is gonna dump.\n\nAlso this can prevent to exit while exiting queue is too long, same for depositing while pending queue is too long.\n\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "validators_total_balance{state=\"Active\"} / 10e8",
     "legendFormat": "Active"
    },
    {
     "expr": "validators_total_balance{state=\"Pending\"} / 10e8",
     "legendFormat": "Pending"
    },
    {
     "expr": "validators_total_balance{state=\"Exiting\"} / 10e8",
     "legendFormat": "Exiting"
    },
    {
     "expr": "beacon_prev_epoch_target_gwei/beacon_prev_epoch_active_gwei*100",
     "legendFormat": "Participation rate"
    }
   ]
  },
  {
   "title": "Node process started",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"$node_job\"})/3600"
    }
   ]
  },
  { "title": "All alerts", "type": "alertlist", "gridPos": { "h": 10, "w": 5, "x": 19, "y": 15 } },
  {
   "title": "Slots behind",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot",
     "legendFormat": "Slots behind"
    }
   ]
  },
  {
   "title": "Peers connected",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\"}"
    }
   ]
  },
  {
   "title": "Current Slot",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_slot" }
   ]
  },
  {
   "title": "Hourly log type counter",
   "type": "bargauge",
   "description": "This panel won't have consistant values during the first hour of the node started process",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(delta(log_entries_total{job=\"$node_job\", level=\"error\"}[1h]) > 0)",
     "legendFormat": "error"
    },
    {
     "expr": "sum(delta(log_entries_total{job=\"$node_job\", level=\"warning\"}[1h]) > 0)",
     "legendFormat": "warning"
    }
   ]
  },
  {
   "title": "Warn: The process just restarted",
   "type": "graph",
   "description": "This alert is useful only for people who has automatic restart of the process after crash. \nThis can be made for example by using the prysm.bat file on windows with \"set PRYSM_AUTORESTART=true&\", or with docker with \"--restart always\"",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"beacon node\"})/3600",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "(time()-process_start_time_seconds{job=\"validator\"})/3600"
    }
   ]
  },
  {
   "title": "Alert: 50 slots behind",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot",
     "legendFormat": "node slots behind"
    }
   ]
  },
  {
   "title": "Alert: Process down",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"beacon node\"}",
     "legendFormat": "beacon node"
    },
    {
     "expr": "up{job=\"validator\"}",
     "legendFormat": "validator"
    }
   ]
  },
  {
   "title": "Alert: Hourly earning <= 0",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(validator_balance) - sum(validator_balance offset 1h) - count(validator_balance > 16)*32 + count(validator_balance offset 1h > 0)*32",
     "legendFormat": "validators earning on 1h"
    }
   ]
  },
  {
   "title": "Alert: 50 errors  or 100 warns  in 1h",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(log_entries_total{job=\"beacon node\", level=\"error\"}[1h]) > 0) ",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(delta(log_entries_total{job=\"beacon node\", level=\"warning\"}[1h]) > 0)",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Alert: Validator has been slashed",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(validator_statuses, \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")",
     "legendFormat": "{{pubkey}}"
    }
   ]
  },
  {
   "title": "Alert: Participation rate < 66%",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "beacon_prev_epoch_target_gwei/beacon_prev_epoch_active_gwei*100"
    }
   ]
  }
 ]
}